#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("xamarinlab.Droid.Resource", IsApplication=true)]

namespace xamarinlab.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LoginScreen.Resource.Drawable.alert = global::xamarinlab.Droid.Resource.Drawable.alert;
			global::LoginScreen.Resource.Drawable.arrow = global::xamarinlab.Droid.Resource.Drawable.arrow;
			global::LoginScreen.Resource.Drawable.bg_login = global::xamarinlab.Droid.Resource.Drawable.bg_login;
			global::LoginScreen.Resource.Drawable.button_login = global::xamarinlab.Droid.Resource.Drawable.button_login;
			global::LoginScreen.Resource.Drawable.button_login_pressed = global::xamarinlab.Droid.Resource.Drawable.button_login_pressed;
			global::LoginScreen.Resource.Drawable.button_login_selector = global::xamarinlab.Droid.Resource.Drawable.button_login_selector;
			global::LoginScreen.Resource.Drawable.button_register = global::xamarinlab.Droid.Resource.Drawable.button_register;
			global::LoginScreen.Resource.Drawable.button_register_pressed = global::xamarinlab.Droid.Resource.Drawable.button_register_pressed;
			global::LoginScreen.Resource.Drawable.button_register_selector = global::xamarinlab.Droid.Resource.Drawable.button_register_selector;
			global::LoginScreen.Resource.Drawable.button_reset = global::xamarinlab.Droid.Resource.Drawable.button_reset;
			global::LoginScreen.Resource.Drawable.button_reset_pressed = global::xamarinlab.Droid.Resource.Drawable.button_reset_pressed;
			global::LoginScreen.Resource.Drawable.button_reset_selector = global::xamarinlab.Droid.Resource.Drawable.button_reset_selector;
			global::LoginScreen.Resource.Drawable.divider_bottom = global::xamarinlab.Droid.Resource.Drawable.divider_bottom;
			global::LoginScreen.Resource.Drawable.divider_top = global::xamarinlab.Droid.Resource.Drawable.divider_top;
			global::LoginScreen.Resource.Drawable.edittext_bg_selector = global::xamarinlab.Droid.Resource.Drawable.edittext_bg_selector;
			global::LoginScreen.Resource.Drawable.edittext_textcolor_selector = global::xamarinlab.Droid.Resource.Drawable.edittext_textcolor_selector;
			global::LoginScreen.Resource.Drawable.Icon = global::xamarinlab.Droid.Resource.Drawable.Icon;
			global::LoginScreen.Resource.Drawable.image_password = global::xamarinlab.Droid.Resource.Drawable.image_password;
			global::LoginScreen.Resource.Drawable.image_password_active = global::xamarinlab.Droid.Resource.Drawable.image_password_active;
			global::LoginScreen.Resource.Drawable.image_username = global::xamarinlab.Droid.Resource.Drawable.image_username;
			global::LoginScreen.Resource.Drawable.image_username_active = global::xamarinlab.Droid.Resource.Drawable.image_username_active;
			global::LoginScreen.Resource.Drawable.password_right_selector = global::xamarinlab.Droid.Resource.Drawable.password_right_selector;
			global::LoginScreen.Resource.Drawable.textfield = global::xamarinlab.Droid.Resource.Drawable.textfield;
			global::LoginScreen.Resource.Drawable.textfield_active = global::xamarinlab.Droid.Resource.Drawable.textfield_active;
			global::LoginScreen.Resource.Drawable.username_right_selector = global::xamarinlab.Droid.Resource.Drawable.username_right_selector;
			global::LoginScreen.Resource.Id.bottomSpace = global::xamarinlab.Droid.Resource.Id.bottomSpace;
			global::LoginScreen.Resource.Id.confirmPasswordEdit = global::xamarinlab.Droid.Resource.Id.confirmPasswordEdit;
			global::LoginScreen.Resource.Id.emailEdit = global::xamarinlab.Droid.Resource.Id.emailEdit;
			global::LoginScreen.Resource.Id.errorLayout = global::xamarinlab.Droid.Resource.Id.errorLayout;
			global::LoginScreen.Resource.Id.errorMessage = global::xamarinlab.Droid.Resource.Id.errorMessage;
			global::LoginScreen.Resource.Id.fake = global::xamarinlab.Droid.Resource.Id.fake;
			global::LoginScreen.Resource.Id.forgotLayout = global::xamarinlab.Droid.Resource.Id.forgotLayout;
			global::LoginScreen.Resource.Id.forgotText = global::xamarinlab.Droid.Resource.Id.forgotText;
			global::LoginScreen.Resource.Id.loginButton = global::xamarinlab.Droid.Resource.Id.loginButton;
			global::LoginScreen.Resource.Id.loginEdit = global::xamarinlab.Droid.Resource.Id.loginEdit;
			global::LoginScreen.Resource.Id.loginLayout = global::xamarinlab.Droid.Resource.Id.loginLayout;
			global::LoginScreen.Resource.Id.loginText = global::xamarinlab.Droid.Resource.Id.loginText;
			global::LoginScreen.Resource.Id.noAccountImage = global::xamarinlab.Droid.Resource.Id.noAccountImage;
			global::LoginScreen.Resource.Id.noAccountSection = global::xamarinlab.Droid.Resource.Id.noAccountSection;
			global::LoginScreen.Resource.Id.noAccountText = global::xamarinlab.Droid.Resource.Id.noAccountText;
			global::LoginScreen.Resource.Id.passwordEdit = global::xamarinlab.Droid.Resource.Id.passwordEdit;
			global::LoginScreen.Resource.Id.registerButton = global::xamarinlab.Droid.Resource.Id.registerButton;
			global::LoginScreen.Resource.Id.registerText = global::xamarinlab.Droid.Resource.Id.registerText;
			global::LoginScreen.Resource.Id.resetButton = global::xamarinlab.Droid.Resource.Id.resetButton;
			global::LoginScreen.Resource.Id.resetText = global::xamarinlab.Droid.Resource.Id.resetText;
			global::LoginScreen.Resource.Id.rootLayout = global::xamarinlab.Droid.Resource.Id.rootLayout;
			global::LoginScreen.Resource.Id.titleLayout = global::xamarinlab.Droid.Resource.Id.titleLayout;
			global::LoginScreen.Resource.Layout.a_login = global::xamarinlab.Droid.Resource.Layout.a_login;
			global::LoginScreen.Resource.Layout.a_register = global::xamarinlab.Droid.Resource.Layout.a_register;
			global::LoginScreen.Resource.Layout.a_reset = global::xamarinlab.Droid.Resource.Layout.a_reset;
			global::LoginScreen.Resource.Layout.a_validationerror = global::xamarinlab.Droid.Resource.Layout.a_validationerror;
			global::LoginScreen.Resource.String.library_name = global::xamarinlab.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_login = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_login = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_login_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_login_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_register = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_register_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_register_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_reset = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_reset_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_reset_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int divider_bottom = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int divider_top = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int edittext_bg_selector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int edittext_textcolor_selector = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int image_password = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int image_password_active = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int image_username = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int image_username_active = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int img2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int monoandroidsplash = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int password_right_selector = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int textfield = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int textfield_active = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int user = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int username_right_selector = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int bottomSpace = 2131099661;
			
			// aapt resource value: 0x7f06001b
			public const int btnClear = 2131099675;
			
			// aapt resource value: 0x7f060022
			public const int btnLogin = 2131099682;
			
			// aapt resource value: 0x7f060011
			public const int confirmPasswordEdit = 2131099665;
			
			// aapt resource value: 0x7f06001d
			public const int editText1 = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int editText2 = 2131099680;
			
			// aapt resource value: 0x7f060010
			public const int emailEdit = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int errorLayout = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int errorMessage = 2131099669;
			
			// aapt resource value: 0x7f060008
			public const int fake = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int forgotLayout = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int forgotText = 2131099655;
			
			// aapt resource value: 0x7f06001a
			public const int getMembers = 2131099674;
			
			// aapt resource value: 0x7f060024
			public const int imgUser = 2131099684;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout1 = 2131099671;
			
			// aapt resource value: 0x7f06001e
			public const int linearLayout3 = 2131099678;
			
			// aapt resource value: 0x7f060021
			public const int linearLayout4 = 2131099681;
			
			// aapt resource value: 0x7f060005
			public const int loginButton = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int loginEdit = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int loginLayout = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int loginText = 2131099650;
			
			// aapt resource value: 0x7f060023
			public const int lstMembers = 2131099683;
			
			// aapt resource value: 0x7f06000a
			public const int noAccountImage = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int noAccountSection = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int noAccountText = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int passwordEdit = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int registerButton = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int registerText = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int resetButton = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int resetText = 2131099666;
			
			// aapt resource value: 0x7f060000
			public const int rootLayout = 2131099648;
			
			// aapt resource value: 0x7f060018
			public const int tableLayout1 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int tableRow1 = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int textView1 = 2131099670;
			
			// aapt resource value: 0x7f06001c
			public const int textView2 = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int textView4 = 2131099679;
			
			// aapt resource value: 0x7f06000e
			public const int titleLayout = 2131099662;
			
			// aapt resource value: 0x7f060027
			public const int txtDepartment = 2131099687;
			
			// aapt resource value: 0x7f060025
			public const int txtName = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int txtSurname = 2131099686;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int a_login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int a_register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int a_reset = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int a_validationerror = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Help = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MembersListView = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
